openapi: 3.0.0
servers:
  - url: 'https://localhost:8888/api/v1/'
info:
  description: >-
    This is the public JSON REST API for the Express API Boilerplate.
  version: 1.0.0
  title: Express API Boilerplate 
  license:
    name: Apache-2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'

externalDocs:
  description: Find out more about Express API Boilerplate
  url: 'https://github.com/anthonybudd/express-api-boilerplate'

tags:
  - name: Auth
    description: Auth Methods

paths:
  '/auth/login':
    post:
      tags:
        - Auth
      summary: Generate an access token
      description: ''
      responses:
        '200':
          description: Successful login response
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                    example: ey.... 
        '401':
          description: Invalid input
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email: 
                  type: string
                  example: user@exmaple.com
                password:
                  type: string
                  example: Password@1234

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer

