apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: express-api-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.org/client-max-body-size: "50m"
spec:
  tls:
  - hosts:
    - api.EXAMPLE.COM
    secretName: express-api-tls
  rules:
    - host: api.EXAMPLE.COM
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: express-api-api
                port:
                  number: 80
